[package]
name = "k8s-plugin-rust"
version = "0.1.0"
edition = "2021"
description = "Kubernetes Admission Plugins reimplemented in Rust"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0.49"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[dev-dependencies]
